#!/usr/bin/env python3
"""Stop hook: reusable-profile writes require a same-day closed loop.

It inspects only this session's transcript. When the session wrote a
data/companies/<issuer_id>.json profile, it requires:

  1. a same-day ledger line naming a profile or selection command
  2. a profile-log calibration generated today

The hook fails open when its input, transcript, ledger, or an existing calibration file
cannot be read. A missing required file is not an unreadable file and therefore blocks.
"""
import datetime
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from write_targets import from_tool_use  # noqa: E402

ALLOW = 0
PROFILE_PATH = re.compile(
    r"(?:^|/)data/companies/([A-Za-z0-9][A-Za-z0-9._-]{0,79})\.json$"
)


def allow() -> int:
    print(json.dumps({"decision": "approve"}))
    return ALLOW


def block(reason: str) -> int:
    print(json.dumps({"decision": "block", "reason": reason}))
    return ALLOW


def written_profiles(raw: str) -> set[str]:
    issuers = set()
    for line in raw.splitlines():
        if "data/companies/" not in line:
            continue
        try:
            event = json.loads(line)
        except Exception:  # noqa: BLE001
            continue
        for item in (event.get("message") or {}).get("content") or []:
            if not isinstance(item, dict) or item.get("type") != "tool_use":
                continue
            written, _unresolved = from_tool_use(
                str(item.get("name") or ""), item.get("input") or {}
            )
            for target in written:
                match = PROFILE_PATH.search(target)
                if match and not match.group(1).startswith("_"):
                    issuers.add(match.group(1))
    return issuers


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except Exception:  # noqa: BLE001
        return allow()
    if payload.get("stop_hook_active"):
        return allow()

    transcript = payload.get("transcript_path")
    if not transcript:
        return allow()
    try:
        raw = Path(transcript).read_text()
    except Exception:  # noqa: BLE001
        return allow()

    touched = written_profiles(raw)
    if not touched:
        return allow()

    root = Path(__file__).resolve().parent.parent.parent
    today = datetime.date.today().isoformat()
    try:
        ledger = (root / "data" / "ledger.md").read_text()
    except Exception:  # noqa: BLE001
        return allow()

    missing = []
    command_re = re.compile(
        r"\b(?:run profile [A-Z0-9.-]{1,10}|"
        r"run profile --campaign CAMP-\d{8}-\d{2}|"
        r"run selection CAMP-\d{8}-\d{2})\b"
    )
    if not any(line.startswith(today) and command_re.search(line)
               for line in ledger.splitlines()):
        missing.append(
            f"a ledger line dated {today} naming `run profile` or `run selection`"
        )
    for issuer_id in sorted(touched):
        if not (root / "data" / "companies" / f"{issuer_id}.json").exists():
            missing.append(f"the touched profile data/companies/{issuer_id}.json")

    log = root / "data" / "companies" / "_profile-log.json"
    if not log.exists():
        missing.append(
            "data/companies/_profile-log.json generated by "
            "`python3 tools/profile_calibrate.py`"
        )
    else:
        try:
            generated = str(
                (json.loads(log.read_text()).get("calibration") or {})
                .get("generated_at") or ""
            )
        except Exception:  # noqa: BLE001
            return allow()
        if not generated.startswith(today):
            missing.append(
                "a profile-log calibration regenerated today: "
                "run `python3 tools/profile_calibrate.py`"
            )

    if not missing:
        return allow()
    return block(
        "This session wrote a reusable issuer profile, so the profile loop must close "
        "before it ends. Still missing: " + "; ".join(missing) + ". "
        "Then run `python3 tools/check_profile.py` before committing."
    )


if __name__ == "__main__":
    raise SystemExit(main())
