#!/usr/bin/env python3
"""Stop hook: reusable-profile writes require a same-day closed loop.

It inspects only this session's transcript. When the session wrote a
data/companies/<issuer_id>.json profile, it requires:

  1. a same-day ledger line naming a profile or selection command
  2. a profile-log calibration generated today

The hook fails open when its input, transcript, ledger, or an existing calibration file
cannot be read. A missing required file is not an unreadable file and therefore blocks.
"""
import datetime
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from write_targets import from_tool_use  # noqa: E402

ALLOW = 0
ROOT = Path(__file__).resolve().parent.parent.parent
UTC = datetime.timezone.utc
PROFILE_PATH = re.compile(
    r"(?:^|/)data/companies/([A-Za-z0-9][A-Za-z0-9._-]{0,79})\.json$"
)


def allow() -> int:
    print(json.dumps({"decision": "approve"}))
    return ALLOW


def block(reason: str) -> int:
    print(json.dumps({"decision": "block", "reason": reason}))
    return ALLOW


def utc_date(timestamp: object) -> datetime.date:
    """Return a timestamp's UTC date, rejecting timezone-naive values."""
    value = str(timestamp or "").strip()
    if value.endswith("Z"):
        value = value[:-1] + "+00:00"
    parsed = datetime.datetime.fromisoformat(value)
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        raise ValueError("timestamp must include a timezone")
    return parsed.astimezone(UTC).date()


def utc_today() -> datetime.date:
    return datetime.datetime.now(UTC).date()


def ledger_has_same_day(
    ledger: str, command_re: re.Pattern[str], day: datetime.date
) -> bool:
    same_day = False
    for line in ledger.splitlines():
        if not command_re.search(line):
            continue
        raw_timestamp, separator, _rest = line.partition("|")
        if not separator or not raw_timestamp.strip():
            continue
        same_day = utc_date(raw_timestamp) == day or same_day
    return same_day


def written_profiles(raw: str) -> set[str]:
    issuers = set()
    for line in raw.splitlines():
        if "data/companies/" not in line:
            continue
        try:
            event = json.loads(line)
        except Exception:  # noqa: BLE001
            continue
        for item in (event.get("message") or {}).get("content") or []:
            if not isinstance(item, dict) or item.get("type") != "tool_use":
                continue
            written, _unresolved = from_tool_use(
                str(item.get("name") or ""), item.get("input") or {}
            )
            for target in written:
                match = PROFILE_PATH.search(target)
                if match and not match.group(1).startswith("_"):
                    issuers.add(match.group(1))
    return issuers


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except Exception:  # noqa: BLE001
        return allow()
    if payload.get("stop_hook_active"):
        return allow()

    transcript = payload.get("transcript_path")
    if not transcript:
        return allow()
    try:
        raw = Path(transcript).read_text()
    except Exception:  # noqa: BLE001
        return allow()

    touched = written_profiles(raw)
    if not touched:
        return allow()

    today = utc_today()
    try:
        ledger = (ROOT / "data" / "ledger.md").read_text()
    except Exception:  # noqa: BLE001
        return allow()

    missing = []
    command_re = re.compile(
        r"\b(?:run profile [A-Z0-9.-]{1,10}|"
        r"run profile --campaign CAMP-\d{8}-\d{2}|"
        r"run selection CAMP-\d{8}-\d{2})\b"
    )
    try:
        same_day_ledger = ledger_has_same_day(ledger, command_re, today)
    except Exception:  # noqa: BLE001
        return allow()
    if not same_day_ledger:
        missing.append(
            f"a ledger line dated {today.isoformat()} naming `run profile` or "
            "`run selection`"
        )
    for issuer_id in sorted(touched):
        if not (ROOT / "data" / "companies" / f"{issuer_id}.json").exists():
            missing.append(f"the touched profile data/companies/{issuer_id}.json")

    log = ROOT / "data" / "companies" / "_profile-log.json"
    if not log.exists():
        missing.append(
            "data/companies/_profile-log.json generated by "
            "`python3 tools/profile_calibrate.py`"
        )
    else:
        try:
            generated = str(
                (json.loads(log.read_text()).get("calibration") or {})
                .get("generated_at") or ""
            )
        except Exception:  # noqa: BLE001
            return allow()
        if generated:
            try:
                generated_today = utc_date(generated) == today
            except Exception:  # noqa: BLE001
                return allow()
        else:
            generated_today = False
        if not generated_today:
            missing.append(
                "a profile-log calibration regenerated today: "
                "run `python3 tools/profile_calibrate.py`"
            )

    if not missing:
        return allow()
    return block(
        "This session wrote a reusable issuer profile, so the profile loop must close "
        "before it ends. Still missing: " + "; ".join(missing) + ". "
        "Then run `python3 tools/check_profile.py` before committing."
    )


if __name__ == "__main__":
    raise SystemExit(main())
