#!/usr/bin/env python3
"""Stop hook: issuer-universe writes require a same-day closed loop.

It inspects only this session's transcript. When the session wrote a normalized
data/mappings/<chain>.json map, it requires:

  1. a same-day ledger line naming `run universe <chain>` for each touched map
  2. a map-log calibration generated today

The hook fails open when its input, transcript, ledger, or an existing calibration file
cannot be read. A missing required file is not an unreadable file and therefore blocks.
"""
import datetime
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from write_targets import from_tool_use  # noqa: E402

ALLOW = 0
MAPPING_PATH = re.compile(r"(?:^|/)data/mappings/([a-z0-9-]{2,40})\.json$")


def allow() -> int:
    print(json.dumps({"decision": "approve"}))
    return ALLOW


def block(reason: str) -> int:
    print(json.dumps({"decision": "block", "reason": reason}))
    return ALLOW


def written_mappings(raw: str) -> set[str]:
    slugs = set()
    for line in raw.splitlines():
        if "data/mappings/" not in line:
            continue
        try:
            event = json.loads(line)
        except Exception:  # noqa: BLE001
            continue
        for item in (event.get("message") or {}).get("content") or []:
            if not isinstance(item, dict) or item.get("type") != "tool_use":
                continue
            written, _unresolved = from_tool_use(
                str(item.get("name") or ""), item.get("input") or {}
            )
            for target in written:
                match = MAPPING_PATH.search(target)
                if match:
                    slugs.add(match.group(1))
    return slugs


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except Exception:  # noqa: BLE001
        return allow()
    if payload.get("stop_hook_active"):
        return allow()

    transcript = payload.get("transcript_path")
    if not transcript:
        return allow()
    try:
        raw = Path(transcript).read_text()
    except Exception:  # noqa: BLE001
        return allow()

    touched = written_mappings(raw)
    if not touched:
        return allow()

    root = Path(__file__).resolve().parent.parent.parent
    today = datetime.date.today().isoformat()
    try:
        ledger = (root / "data" / "ledger.md").read_text()
    except Exception:  # noqa: BLE001
        return allow()

    missing = []
    ledger_lines = [line for line in ledger.splitlines() if line.startswith(today)]
    for slug in sorted(touched):
        command_re = re.compile(rf"\brun universe {re.escape(slug)}\b")
        if not any(command_re.search(line) for line in ledger_lines):
            missing.append(
                f"a ledger line dated {today} naming `run universe {slug}`"
            )
        if not (root / "data" / "mappings" / f"{slug}.json").exists():
            missing.append(f"the touched issuer map data/mappings/{slug}.json")

    log = root / "data" / "chains" / "_map-log.json"
    if not log.exists():
        missing.append(
            "data/chains/_map-log.json generated by `python3 tools/map_calibrate.py`"
        )
    else:
        try:
            generated = str(
                (json.loads(log.read_text()).get("calibration") or {})
                .get("generated_at") or ""
            )
        except Exception:  # noqa: BLE001
            return allow()
        if not generated.startswith(today):
            missing.append(
                "a map-log calibration regenerated today: "
                "run `python3 tools/map_calibrate.py`"
            )

    if not missing:
        return allow()
    return block(
        "This session wrote an issuer universe, so the universe loop must close before "
        "it ends. Still missing: " + "; ".join(missing) + ". "
        "Then run `python3 tools/check_map.py` before committing."
    )


if __name__ == "__main__":
    raise SystemExit(main())
